### ISSUE TITLE
Doesn't compile, missing PlugInInterfaces.dll

### ISSUE THREAD

**Issue by thnk2wn** [Inflectra/spira5_jira-datasync#1]
Sample doesn't compile:

<pre>
The type or namespace name 'IDataSyncPlugIn' could not be found (are you missing a using directive or an assembly reference?)
</pre>

It references ..\..\Assemblies\PlugInInterfaces.dll which is not in the repo. Where does this DLL reside? Can it be found on nuget instead?

<img width="773" alt="spira" src="https://user-images.githubusercontent.com/120529/47186070-38ac6a00-d2e4-11e8-97a2-47e85b002cb3.png">

**Comment by yipmarvel** [comment]
You need to first install the Desktop Data Sync from Inflectra. This installs the required DLL, which you can then either copy into or reference in the solution. We will amend the readme to provide more detailed instructions.

**Comment by yipmarvel** [comment]
The dll does not rely on COM interop as far as I know. I thought that you’d got this working a couple of weeks back so my apologies for the delay in replying here. We’ll consider a nuget package for this. Thanks
